<?php
$role = $role ?? 'Administrator';
$backUrl = $backUrl ?? '/';
$success = sessionSuccess();
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Settings - DormSync</title><style>*{box-sizing:border-box}body{background:#f7f9fc;color:#172033;font-family:Arial,sans-serif;margin:0}.topbar{align-items:center;background:#fff;border-bottom:1px solid #e7ebf2;display:flex;justify-content:space-between;padding:18px 6%}.brand{color:#172b4d;font-size:21px;font-weight:700}.topbar a{color:#2563eb;font-size:14px;text-decoration:none}main{margin:0 auto;max-width:760px;padding:38px 24px}.panel{background:#fff;border:1px solid #e7ebf2;border-radius:8px;padding:24px}h1{font-size:28px;margin:0 0 8px}.intro{color:#718096;margin:0 0 24px}.message{background:#ecfdf5;border-radius:6px;color:#166534;margin-bottom:14px;padding:11px 12px}label{color:#475569;display:block;font-size:13px;font-weight:600;margin:14px 0 6px}input,button{border:1px solid #cbd5e1;border-radius:6px;font:inherit;padding:11px 12px;width:100%}button{background:#2563eb;border-color:#2563eb;color:#fff;cursor:pointer;font-weight:600;margin-top:18px}</style></head>
<body><header class="topbar"><div class="brand">DormSync<sup>®</sup></div><a href="<?= htmlspecialchars($backUrl) ?>">Back to dashboard</a></header><main><h1><?= htmlspecialchars($role) ?> Settings</h1><p class="intro">Update the system settings available to your role.</p><?php if ($success): ?><div class="message"><?= htmlspecialchars($success) ?></div><?php endif; ?><section class="panel"><form method="post" action="/admin/settings-update"><label for="timezone">Application timezone</label><input id="timezone" name="timezone" value="Asia/Kathmandu"><label for="notifications">Notification preference</label><input id="notifications" name="notifications" value="Enabled"><button type="submit">Save Settings</button></form></section></main></body></html>
