<?php
require_once __DIR__ . '/../models/User.php';
require_once __DIR__ . '/../models/Student.php';
require_once __DIR__ . '/../models/Warden.php';
require_once __DIR__ . '/../models/Room.php';
require_once __DIR__ . '/../models/Fee.php';
require_once __DIR__ . '/../models/Complaint.php';
require_once __DIR__ . '/../models/Visitor.php';
require_once __DIR__ . '/../models/WardenInvitation.php';
require_once __DIR__ . '/../models/Notice.php';
require_once __DIR__ . '/../models/Hostel.php';
require_once __DIR__ . '/../helpers/auth.php';
require_once __DIR__ . '/../helpers/redirect.php';
require_once __DIR__ . '/../helpers/session.php';

class AdminController {
    public static function createWardenInvitation() {
        AdminMiddleware::handle();
        $email = $_POST['email'] ?? '';
        $expiresAt = str_replace('T', ' ', $_POST['expires_at'] ?? date('Y-m-d H:i:s', strtotime('+7 days')));
        $errors = validate([
            'email' => $email,
            'expires_at' => $expiresAt
        ], [
            'email' => 'required|email',
            'expires_at' => 'required'
        ]);

        if (!empty($errors)) {
            redirectWithErrors('/admin/users', $errors);
            return;
        }

        $code = strtoupper(bin2hex(random_bytes(4)));
        WardenInvitation::create($email, $code, $expiresAt, currentUserId());
        $_SESSION['invitation_code'] = $code;
        $_SESSION['invitation_email'] = $email;
        $_SESSION['invitation_expires_at'] = $expiresAt;
        redirectWithSuccess('/admin/users', 'Warden invitation created.');
    }

    public static function dashboard() {
        AdminMiddleware::handle();
        Hostel::ensureTable();
        $totalHostels = db()->query("SELECT COUNT(*) FROM hostels WHERE status = 'active'")->fetchColumn();
        $stats = [
            'total_users' => User::count(),
            'total_students' => Student::count(),
            'total_wardens' => Warden::count(),
            'total_rooms' => Room::count(),
            'total_hostels' => $totalHostels,
            'available_rooms' => Room::countAvailable(),
            'occupied_rooms' => Room::countOccupied(),
            'pending_complaints' => Complaint::countPending(),
            'unpaid_fees' => Fee::countUnpaid(),
            'pending_wardens' => db()->query("SELECT COUNT(*) FROM users WHERE role = 'warden' AND account_status = 'pending'")->fetchColumn(),
            'total_collected' => Fee::getTotalCollected(),
            'total_due' => Fee::getTotalDue()
        ];
        
        $recentActivities = db()->query("SELECT * FROM logs ORDER BY created_at DESC LIMIT 10")->fetchAll();
        $monthlyOverview = db()->query("SELECT DATE_FORMAT(created_at, '%b') AS month,
                               COUNT(*) AS registrations,
                               COALESCE((SELECT SUM(amount) FROM fees WHERE status = 'paid' AND DATE_FORMAT(paid_at, '%Y-%m') = DATE_FORMAT(u.created_at, '%Y-%m')), 0) AS revenue
                        FROM users u
                        WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL 5 MONTH)
                        GROUP BY DATE_FORMAT(created_at, '%Y-%m'), DATE_FORMAT(created_at, '%b')
                        ORDER BY DATE_FORMAT(created_at, '%Y-%m')")->fetchAll();

        view('admin/dashboard', compact('stats', 'recentActivities', 'monthlyOverview'));
    }

    public static function users() {
        AdminMiddleware::handle();
        $users = User::all();
        $invitations = WardenInvitation::all();
        view('admin/users', compact('users', 'invitations'));
    }

    public static function userCreate() {
        AdminMiddleware::handle();
        view('admin/users-create');
    }

    public static function userStore() {
        AdminMiddleware::handle();
        $data = $_POST;

        if (($data['role'] ?? '') === ROLE_WARDEN) {
            redirectWithError('/admin/users', 'Wardens must register with an invitation code generated by an administrator.');
            return;
        }

        $errors = validate($data, [
            'username' => 'required|min:3|unique:users',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
            'full_name' => 'required|min:2',
            'role' => 'required|in:student,warden,admin',
            'phone' => 'numeric'
        ]);

        if (!empty($errors)) {
            redirectWithErrors('/admin/users', $errors);
            return;
        }

        $userId = User::create([
            'username' => $data['username'],
            'email' => $data['email'],
            'password_hash' => password_hash($data['password'], PASSWORD_DEFAULT),
            'role' => $data['role'],
            'full_name' => $data['full_name'],
            'phone' => $data['phone'] ?? ''
        ]);

        // Create role-specific record
        if ($data['role'] === ROLE_STUDENT) {
            Student::create([
                'user_id' => $userId,
                'student_id' => $data['student_id'] ?? 'S' . time(),
                'parent_contact' => $data['parent_contact'] ?? '',
                'address' => $data['address'] ?? ''
            ]);
        } elseif ($data['role'] === ROLE_WARDEN) {
            Warden::create([
                'user_id' => $userId,
                'assigned_block' => $data['assigned_block'] ?? ''
            ]);
        }

        redirectWithSuccess('/admin/users', 'User created successfully!');
    }

    public static function userEdit($id) {
        AdminMiddleware::handle();
        $user = User::find($id);
        if (!$user) {
            redirectWithError('/admin/users', 'User not found');
            return;
        }
        view('admin/users-edit', compact('user'));
    }

    public static function userUpdate($id) {
        AdminMiddleware::handle();
        $data = $_POST;

        $errors = validate($data, [
            'email' => 'required|email',
            'full_name' => 'required|min:2',
            'phone' => 'numeric'
        ]);

        if (!empty($errors)) {
            redirectWithErrors('/admin/users-edit/' . $id, $errors);
            return;
        }

        $updateData = [
            'email' => $data['email'],
            'full_name' => $data['full_name'],
            'phone' => $data['phone'] ?? ''
        ];

        if (!empty($data['password'])) {
            if (strlen($data['password']) < 6) {
                redirectWithError('/admin/users-edit/' . $id, 'Password must be at least 6 characters');
                return;
            }
            $updateData['password_hash'] = password_hash($data['password'], PASSWORD_DEFAULT);
        }

        User::update($id, $updateData);
        redirectWithSuccess('/admin/users', 'User updated successfully!');
    }

    public static function userDelete($id) {
        AdminMiddleware::handle();
        if ($id == currentUserId()) {
            redirectWithError('/admin/users', 'You cannot delete yourself');
            return;
        }
        User::delete($id);
        redirectWithSuccess('/admin/users', 'User deleted successfully!');
    }

    public static function userStatus($id) {
        AdminMiddleware::handle();
        if ($id == currentUserId()) {
            redirectWithError('/admin/users', 'You cannot deactivate yourself.');
            return;
        }
        $user = User::find($id);
        if (!$user) {
            redirectWithError('/admin/users', 'User not found.');
            return;
        }
        $status = ($_POST['status'] ?? '') === 'approved' ? 'approved' : 'rejected';
        User::update($id, ['account_status' => $status]);
        redirectWithSuccess('/admin/users', 'Account status updated.');
    }

    public static function students() {
        AdminMiddleware::handle();
        $search = trim($_GET['search'] ?? '');
        $stmt = db()->prepare("SELECT s.*, u.email, u.full_name, u.phone, r.room_number, r.block FROM students s JOIN users u ON s.user_id = u.id LEFT JOIN rooms r ON s.room_id = r.id WHERE (? = '' OR u.full_name LIKE ? OR s.student_id LIKE ? OR u.email LIKE ?) ORDER BY u.full_name");
        $term = '%' . $search . '%';
        $stmt->execute([$search, $term, $term, $term]);
        $students = $stmt->fetchAll();
        $rows = $students;
        $title = 'Students'; $backUrl = '/admin/dashboard';
        $columns = ['Name' => 'full_name', 'Student ID' => 'student_id', 'Email' => 'email', 'Room' => 'room_number', 'Phone' => 'phone'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows', 'search'));
    }

    public static function rooms() {
        AdminMiddleware::handle();
        $rooms = Room::all();
        $rows = $rooms;
        $title = 'Rooms'; $backUrl = '/admin/dashboard';
        $columns = ['Room' => 'room_number', 'Block' => 'block', 'Floor' => 'floor', 'Capacity' => 'capacity', 'Occupied' => 'current_occupancy', 'Status' => 'status'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows'));
    }

    public static function hostels() {
        AdminMiddleware::handle();
        $hostels = Hostel::all();
        view('admin/hostels', compact('hostels'));
    }

    public static function hostelStore() {
        AdminMiddleware::handle();
        $data = $_POST;
        $errors = validate($data, ['name' => 'required|max:100', 'block' => 'required|max:10', 'status' => 'required|in:active,inactive']);
        if (!empty($errors)) {
            redirectWithErrors('/admin/hostels', $errors);
            return;
        }
        Hostel::create($data);
        redirectWithSuccess('/admin/hostels', 'Hostel created successfully.');
    }

    public static function hostelUpdate($id) {
        AdminMiddleware::handle();
        $data = $_POST;
        $errors = validate($data, ['name' => 'required|max:100', 'block' => 'required|max:10', 'status' => 'required|in:active,inactive']);
        if (!empty($errors)) {
            redirectWithErrors('/admin/hostels', $errors);
            return;
        }
        Hostel::update($id, $data);
        redirectWithSuccess('/admin/hostels', 'Hostel updated successfully.');
    }

    public static function fees() {
        AdminMiddleware::handle();
        $fees = Fee::all();
        $students = Student::all();
        $rows = $fees;
        $title = 'Payments'; $backUrl = '/admin/dashboard';
        $columns = ['Student' => 'full_name', 'Student ID' => 'student_id', 'Amount' => 'amount', 'Due date' => 'due_date', 'Status' => 'status'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows'));
    }

    public static function complaints() {
        AdminMiddleware::handle();
        $complaints = Complaint::all();
        $stats = Complaint::getStatistics();
        $rows = $complaints;
        $title = 'Complaints'; $backUrl = '/admin/dashboard';
        $columns = ['Student' => 'full_name', 'Subject' => 'subject', 'Category' => 'category', 'Priority' => 'priority', 'Status' => 'status', 'Created' => 'created_at'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows'));
    }

    public static function visitors() {
        AdminMiddleware::handle();
        $visitors = Visitor::all();
        $rows = $visitors;
        $title = 'Visitors'; $backUrl = '/admin/dashboard';
        $columns = ['Student' => 'full_name', 'Visitor' => 'visitor_name', 'Contact' => 'contact', 'Purpose' => 'purpose', 'Status' => 'status'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows'));
    }

    public static function wardens() {
        AdminMiddleware::handle();
        $wardens = Warden::all();
        $rows = $wardens;
        $title = 'Wardens'; $backUrl = '/admin/dashboard';
        $columns = ['Name' => 'full_name', 'Email' => 'email', 'Phone' => 'phone', 'Block' => 'assigned_block'];
        view('management/table', compact('title', 'backUrl', 'columns', 'rows'));
    }

    public static function reports() {
        AdminMiddleware::handle();
        $occupancyReport = db()->query("SELECT room_number, capacity, current_occupancy, 
                                        (current_occupancy / capacity * 100) as occupancy_percent 
                                        FROM rooms")->fetchAll();
        
        $feeReport = Fee::all();
        $complaintStats = Complaint::getStatistics();
        $studentReport = db()->query("SELECT u.full_name, s.student_id, r.room_number, 
                                     (SELECT COUNT(*) FROM fees WHERE student_id=s.id AND status='unpaid') as unpaid_fees,
                                     (SELECT COUNT(*) FROM complaints WHERE student_id=s.id AND status!='resolved') as open_complaints
                                     FROM students s JOIN users u ON s.user_id = u.id LEFT JOIN rooms r ON s.room_id = r.id")->fetchAll();
        $title = 'Reports'; $backUrl = '/admin/dashboard';
        $sections = [
            ['title' => 'Room occupancy', 'columns' => ['Room' => 'room_number', 'Capacity' => 'capacity', 'Occupied' => 'current_occupancy', 'Occupancy %' => 'occupancy_percent'], 'rows' => $occupancyReport],
            ['title' => 'Student overview', 'columns' => ['Student' => 'full_name', 'Student ID' => 'student_id', 'Room' => 'room_number', 'Unpaid fees' => 'unpaid_fees', 'Open complaints' => 'open_complaints'], 'rows' => $studentReport]
        ];
        view('management/report', compact('title', 'backUrl', 'sections'));
    }

    public static function settings() {
        AdminMiddleware::handle();
        $role = 'Administrator'; $backUrl = '/admin/dashboard';
        view('management/settings', compact('role', 'backUrl'));
    }

    public static function updateSettings() {
        AdminMiddleware::handle();
        // Implement settings update logic
        redirectWithSuccess('/admin/settings', 'Settings updated successfully!');
    }

    public static function profile() {
        AdminMiddleware::handle();
        $admin = User::find(currentUserId());
        view('admin/profile', compact('admin'));
    }

    public static function profileUpdate() {
        AdminMiddleware::handle();
        $data = $_POST;
        $errors = validate($data, ['full_name' => 'required|min:2', 'phone' => 'numeric']);
        if (!empty($errors)) {
            redirectWithErrors('/admin/profile', $errors);
            return;
        }
        $update = ['full_name' => $data['full_name'], 'phone' => $data['phone'] ?? ''];
        if (!empty($data['password'])) {
            if (strlen($data['password']) < 6) {
                redirectWithError('/admin/profile', 'Password must be at least 6 characters.');
                return;
            }
            $update['password_hash'] = password_hash($data['password'], PASSWORD_DEFAULT);
        }
        User::update(currentUserId(), $update);
        $_SESSION['full_name'] = $data['full_name'];
        redirectWithSuccess('/admin/profile', 'Profile updated successfully.');
    }

    public static function notifications() {
        AdminMiddleware::handle();
        $notices = Notice::all();
        view('admin/notifications', compact('notices'));
    }

    public static function noticeCreate() {
        AdminMiddleware::handle();
        view('admin/notice-form');
    }

    public static function noticeStore() {
        AdminMiddleware::handle();
        $data = $_POST;
        $errors = validate($data, ['title' => 'required|max:150', 'message' => 'required', 'scope' => 'required|in:system,hostel']);
        if (!empty($errors)) {
            redirectWithErrors('/admin/notice-create', $errors);
            return;
        }
        Notice::create(['title' => $data['title'], 'message' => $data['message'], 'scope' => $data['scope'], 'block' => $data['block'] ?? '', 'created_by' => currentUserId()]);
        redirectWithSuccess('/admin/notifications', 'Notice published successfully.');
    }

    public static function noticeDelete($id) {
        AdminMiddleware::handle();
        Notice::delete($id);
        redirectWithSuccess('/admin/notifications', 'Notice deleted successfully.');
    }
}
?>